export const LEFT_MENU = {
  CHATS: 'CHATS',
  NEW_GROUP: 'NEW_GROUP',
  CONTACTS: 'CONTACTS',
  SETTINGS: 'SETTINGS',
  HELP: 'HELP',
  ARCHIVED: 'ARCHIVED',
  SAVED: 'SAVED',
  NEW_CHANNEL: 'NEW_CHANNEL',
  NEW_PRIVATE_CHAT: 'NEW_PRIVATE_CHAT',
}
