export const LEFT_MENU = {
  CHATS: 'CHATS',
  NEW_GROUP: 'NEW_GROUP',
  CONTACTS: 'CONTACTS',
  SETTING: 'SETTINGS',
  HELP: 'HELP',
  ARCHIVED: 'ARCHIVED',
  SAVED: 'SAVED',
  NEW_CHANNEL: 'NEW_CHANNEL',
  NEW_PRIVATE_CHAT: 'NEW_PRIVATE_CHAT',
  SETTINGS: {
    EDIT: 'LEFT_MENU_SETTINGS_EDIT',
    GENERAL: 'LEFT_MENU_SETTINGS_GENERAL',
    NOTIFICATIONS: 'LEFT_MENU_SETTINGS_NOTIFICATIONS',
    PRIVACY: 'LEFT_MENU_SETTINGS_PRIVACY',
    LANGUAGE: 'LEFT_MENU_SETTINGS_LANGUAGE',
  },
}

export const MIDDLE_MENU = {
  NO_SELECTED_CHAT: 'MIDDLE_MENU_NO_SELECTED_CHAT',
  CHAT: {
    OPENED: 'MIDDLE_MENU_OPENED_CHAT',
  },
}

export const RIGHT_MENU = {
  CHAT_INFO: 'RIGHT_MENU_CHAT_INFO',
  CHANNEL_INFO: 'RIGHT_MENU_CHANNEL_INFO',
}
